apiVersion: apps/v1
kind: Deployment
metadata:
  name: modernizer-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modernizer-backend
  template:
    metadata:
      labels:
        app: modernizer-backend
    spec:
      containers:
      - name: modernizer-backend
        image: registry.tech4comp.dbis.rwth-aachen.de/rwthacis/modernizer:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
          - name: OLLAMA_URL
            value: "https://quagga-crack-bluejay.ngrok-free.app"
          - name: WEAVIATE_HOST
            value: "weaviate.ba-kovacevic:80"
          - name: OLLAMA_MODEL
            value: "codellama:13b-instruct"
          - name: WEAVIATE_KEY
            valueFrom:
              secretKeyRef:
                name: weaviate
                key: API_key
