apiVersion: v1
kind: Service
metadata:
  name: ollama-webui-service
spec:
  selector:
    app: ollama-webui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # If using NodePort, you can optionally specify the nodePort:
      # nodePort: 30000
