# ollama-chatbot-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-chatbot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-chatbot
  template:
    metadata:
      labels:
        app: ollama-chatbot
    spec:
      containers:
      - name: ollama-chatbot
        image: ghcr.io/ivanfioravanti/chatbot-ollama:main
