---

apiVersion: v1
kind: Service
metadata:
  name: ollama-chatbot-service
spec:
  selector:
    app: ollama-chatbot
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3000
  type: ClusterIP
