---

# ollama-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 443
      targetPort: 11434
  type: ClusterIP
