name: Build Modernizer Image and restart Pod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: | 
        docker build -t registry.tech4comp.dbis.rwth-aachen.de/rwthacis/modernizer:latest .
    - name: Push to registry
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  
        DOCKER_PW: ${{ secrets.DOCKER_PW }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PW registry.tech4comp.dbis.rwth-aachen.de
        docker push registry.tech4comp.dbis.rwth-aachen.de/rwthacis/modernizer:latest
  rollout:
    needs: build
    name: Rollout and Restart Modernizer Deployment
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          kubectl.exe rollout restart deployment modernizer-backend-deployment 
